# Generated by Django 4.0.1 on 2022-01-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Discription', models.TextField()),
                ('Info', models.TextField()),
                ('Highlights', models.TextField()),
                ('R1', models.TextField(default='')),
                ('R2', models.TextField(default='')),
            ],
        ),
    ]
