# Generated by Django 4.0.1 on 2022-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgUrls',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
