# Generated by Django 4.0.1 on 2022-01-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Author',
        ),
    ]
