# Generated by Django 4.0.1 on 2022-01-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0004_remove_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
