# Generated by Django 4.0.1 on 2022-01-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0005_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('memb_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('branch_year_mobilenumber_email_por', models.TextField()),
                ('About', models.TextField()),
                ('Intrests', models.TextField()),
                ('Activities', models.TextField()),
                ('links', models.TextField()),
                ('img', models.TextField()),
                ('R1', models.TextField(default='')),
                ('R2', models.TextField(default='')),
            ],
        ),
    ]
