# Generated by Django 4.0.1 on 2022-01-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
