# Generated by Django 4.0.1 on 2022-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0009_allowedperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Thumbnail_link', models.TextField()),
                ('Link', models.TextField()),
            ],
        ),
    ]
