# Generated by Django 4.0.1 on 2022-02-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0010_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='About',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
