# Generated by Django 4.0.1 on 2022-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0011_publication_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Interviewee', models.TextField()),
                ('Disc', models.TextField()),
                ('Video', models.TextField()),
                ('Link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('Photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Interviewee', models.TextField()),
                ('Disc', models.TextField()),
                ('Video', models.TextField()),
                ('Link', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='Date',
            field=models.CharField(default='', max_length=500),
        ),
    ]
