# Generated by Django 4.0.1 on 2022-02-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0013_rename_disc_photo_group_remove_photo_interviewee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='Thumbnail',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
