# Generated by Django 4.0.1 on 2022-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0014_interview_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Link',
            field=models.TextField(),
        ),
    ]
